application: test-time-sheet
version: 11
runtime: php55
api_version: 1
threadsafe: true

handlers:

- url: /CSS
  static_dir: CSS

- url: /JS
  static_dir: JS

- url: /bootstrap
  static_dir: bootstrap

- url: /Data_table
  static_dir: Data_table

- url: /images
  static_dir: images

- url: /msgbox
  static_dir: msgbox

- url: /menu
  static_dir: menu

- url: /DB_MENU.do
  script: DB_MENU.php

- url: /TSLIB/TSLIB_COMMON.do
  script: TSLIB/TSLIB_COMMON.php

- url: /ACCESSRIGHTS/ERROR_PAGE.do
  script: ACCESSRIGHTS/ERROR_PAGE.php

- url: /ACCESSRIGHTS/FORM_ACCESS_RIGHTS_SEARCH_UPDATE.do
  script: ACCESSRIGHTS/FORM_ACCESS_RIGHTS_SEARCH_UPDATE.php

- url: /ACCESSRIGHTS/DB_ACCESS_RIGHTS_ACCESS_RIGHTS-SEARCH_UPDATE.do
  script: ACCESSRIGHTS/DB_ACCESS_RIGHTS_ACCESS_RIGHTS-SEARCH_UPDATE.php

- url: /ACCESSRIGHTS/FORM_ACCESS_RIGHTS_TERMINATE_SEARCH_UPDATE.do
  script: ACCESSRIGHTS/FORM_ACCESS_RIGHTS_TERMINATE_SEARCH_UPDATE.php

- url: /ACCESSRIGHTS/DB_ACCESS_RIGHTS_TERMINATE-SEARCH_UPDATE.do
  script: ACCESSRIGHTS/DB_ACCESS_RIGHTS_TERMINATE-SEARCH_UPDATE.php

- url: /ACCESSRIGHTS/FORM_ACCESS_RIGHTS_USER_SEARCH_DETAILS.do
  script: ACCESSRIGHTS/FORM_ACCESS_RIGHTS_USER_SEARCH_DETAILS.php

- url: /ACCESSRIGHTS/DB_ACCESS_RIGHTS_USER_SEARCH_DETAIL.do
  script: ACCESSRIGHTS/DB_ACCESS_RIGHTS_USER_SEARCH_DETAIL.php

- url: /ACCESSRIGHTS/FORM_ACCESS_RIGHTS_SITE_MAINTENANCE.do
  script: ACCESSRIGHTS/FORM_ACCESS_RIGHTS_SITE_MAINTENANCE.php

- url: /ACCESSRIGHTS/DB_ACCESS_RIGHTS_SITE_MAINTENANCE.do
  script: ACCESSRIGHTS/DB_ACCESS_RIGHTS_SITE_MAINTENANCE.php

- url: /ADMIN/FORM_ADMIN_REPORT_ENTRY_SEARCH_UPDATE_DELETE.do
  script: ADMIN/FORM_ADMIN_REPORT_ENTRY_SEARCH_UPDATE_DELETE.php

- url: /ADMIN/DB_DAILY_REPORTS_ADMIN_REPORT_ENTRY.do
  script: ADMIN/DB_DAILY_REPORTS_ADMIN_REPORT_ENTRY.php

- url: /ADMIN/DB_DAILY_REPORTS_ADMIN_SEARCH_UPDATE_DELETE.do
  script: ADMIN/DB_DAILY_REPORTS_ADMIN_SEARCH_UPDATE_DELETE.php

- url: /ADMIN/FORM_WEEKLY_REPORT_ENTRY_SEARCH_UPDATE.do
  script: ADMIN/FORM_WEEKLY_REPORT_ENTRY_SEARCH_UPDATE.php

- url: /ADMIN/DB_WEEKLY_REPORT_ADMIN_WEEKLY_REPORT_ENTRY.do
  script: ADMIN/DB_WEEKLY_REPORT_ADMIN_WEEKLY_REPORT_ENTRY.php

- url: /ADMIN/DB_WEEKLY_REPORT_ADMIN_WEEKLY_SEARCH_UPDATE.do
  script: ADMIN/DB_WEEKLY_REPORT_ADMIN_WEEKLY_SEARCH_UPDATE.php

- url: /ADMIN/EMPLOYEE/FORM_ADMIN_EMPLOYEE_ATTENDANCE.do
  script: ADMIN/EMPLOYEE/FORM_ADMIN_EMPLOYEE_ATTENDANCE.php

- url: /ADMIN/EMPLOYEE/DB_REPORT_ATTENDANCE.do
  script: ADMIN/EMPLOYEE/DB_REPORT_ATTENDANCE.php

- url: /ADMIN/EMPLOYEE/FORM_ADMIN_EMPLOYEE_REVENUE.do
  script: ADMIN/EMPLOYEE/FORM_ADMIN_EMPLOYEE_REVENUE.php

- url: /ADMIN/EMPLOYEE/DB_REPORT_REVENUE.do
  script: ADMIN/EMPLOYEE/DB_REPORT_REVENUE.php

- url: /ADMIN/EMPLOYEE/DB_REPORT_ATTENDANCE.do
  script: ADMIN/EMPLOYEE/DB_REPORT_ATTENDANCE.php

- url: /ADMIN/EMPLOYEE/FORM_ADMIN_EMPLOYEE_TICKLER_HISTORY.do
  script: ADMIN/EMPLOYEE/FORM_ADMIN_EMPLOYEE_TICKLER_HISTORY.php

- url: /ADMIN/EMPLOYEE/DB_REPORT_TICKLER_HISTORY.do
  script: ADMIN/EMPLOYEE/DB_REPORT_TICKLER_HISTORY.php

- url: /ADMIN/EMPLOYEE/FORM_ADMIN_EMPLOYEE_BANDWIDTH.do
  script: ADMIN/EMPLOYEE/FORM_ADMIN_EMPLOYEE_BANDWIDTH.php

- url: /ADMIN/EMPLOYEE/DB_REPORT_BANDWIDTH.do
  script: ADMIN/EMPLOYEE/DB_REPORT_BANDWIDTH.php

- url: /ADMIN/EMPLOYEE/FORM_ADMIN_EMPLOYEE_DOOR_ACCESS.do
  script: ADMIN/EMPLOYEE/FORM_ADMIN_EMPLOYEE_DOOR_ACCESS.php

- url: /ADMIN/EMPLOYEE/DB_REPORT_DOOR_ACCESS.do
  script: ADMIN/EMPLOYEE/DB_REPORT_DOOR_ACCESS.php

- url: /ADMIN/EMPLOYEE/FORM_ADMIN_EMPLOYEE_COMPANY_PROPERTY_VERIFICATION.do
  script: ADMIN/EMPLOYEE/FORM_ADMIN_EMPLOYEE_COMPANY_PROPERTY_VERIFICATION.php

- url: /ADMIN/EMPLOYEE/DB_EMPLOYEE_COMPANY_PROPERTY_VERIFICATION.do
  script: ADMIN/EMPLOYEE/DB_EMPLOYEE_COMPANY_PROPERTY_VERIFICATION.php

- url: /ADMIN/EMPLOYEE/FORM_ADMIN_EMPLOYEE_CLOCK_IN_OUT_DETAILS.do
  script: ADMIN/EMPLOYEE/FORM_ADMIN_EMPLOYEE_CLOCK_IN_OUT_DETAILS.php

- url: /ADMIN/EMPLOYEE/DB_REPORT_CLOCK_OUT_MISSED_DETAILS.do
  script: ADMIN/EMPLOYEE/DB_REPORT_CLOCK_OUT_MISSED_DETAILS.php

- url: /ADMIN/EMPLOYEE/DB_REPORT_CLOCK_IN_OUT_DETAILS.do
  script: ADMIN/EMPLOYEE/DB_REPORT_CLOCK_IN_OUT_DETAILS.php

- url: /ADMIN/EMPLOYEE/FORM_ADMIN_EMPLOYEE_DETAILS.do
  script: ADMIN/EMPLOYEE/FORM_ADMIN_EMPLOYEE_DETAILS.php

- url: /ADMIN/EMPLOYEE/DB_EMPLOYEE_DETAILS.do
  script: ADMIN/EMPLOYEE/DB_EMPLOYEE_DETAILS.php

- url: /USER/FORM_USER_REPORT_ENTRY_SEARCH_UPDATE.do
  script: USER/FORM_USER_REPORT_ENTRY_SEARCH_UPDATE.php

- url: /USER/DB_DAILY_REPORTS_USER_REPORT_ENTRY.do
  script: USER/DB_DAILY_REPORTS_USER_REPORT_ENTRY.php

- url: /USER/DB_DAILY_REPORTS_USER_SEARCH_UPDATE.do
  script: USER/DB_DAILY_REPORTS_USER_SEARCH_UPDATE.php

- url: /USER/FORM_USER_REVENUE.do
  script: USER/FORM_USER_REVENUE.php

- url: /USER/DB_DAILY_REPORT_USER_PROJECT_REVENUE.do
  script: USER/DB_DAILY_REPORT_USER_PROJECT_REVENUE.php

- url: /USER/FORM_USER_CLOCK_IN_OUT_DETAILS.do
  script: USER/FORM_USER_CLOCK_IN_OUT_DETAILS.php

- url: /USER/DB_DAILY_REPORTS_USER_CLOCK_IN_OUT_DETAILS.do
  script: USER/DB_DAILY_REPORTS_USER_CLOCK_IN_OUT_DETAILS.php

- url: /USER/DB_DAILY_REPORTS_USER_CLOCK_OUT_MISSED_DETAILS.do
  script: USER/DB_DAILY_REPORTS_USER_CLOCK_OUT_MISSED_DETAILS.php

- url: /SETTINGS/FORM_SETTINGS_CONFIGURATION_ENTRY_SEARCH_UPDATE_DELETE.do
  script: SETTINGS/FORM_SETTINGS_CONFIGURATION_ENTRY_SEARCH_UPDATE_DELETE.php

- url: /SETTINGS/DB_SETTINGS_CONFIGURATION_ENTRY_SEARCH_UPDATE_DELETE.do
  script: SETTINGS/DB_SETTINGS_CONFIGURATION_ENTRY_SEARCH_UPDATE_DELETE.php

- url: /SETTINGS/FORM_SETTINGS_EMAIL_TEMPLATE_ENTRY_SEARCH_UPDATE.do
  script: SETTINGS/FORM_SETTINGS_EMAIL_TEMPLATE_ENTRY_SEARCH_UPDATE.php

- url: /SETTINGS/DB_EMAIL_EMAIL_TEMPLATE_ENTRY.do
  script: SETTINGS/DB_EMAIL_EMAIL_TEMPLATE_ENTRY.php

- url: /SETTINGS/DB_EMAIL_EMAIL_TEMPLATE_SEARCH_UPDATE.do
  script: SETTINGS/DB_EMAIL_EMAIL_TEMPLATE_SEARCH_UPDATE.php

- url: /SETTINGS/FORM_SETTINGS_PUBLIC_HOLIDAY_ENTRY_SEARCH_UPDATE.do
  script: SETTINGS/FORM_SETTINGS_PUBLIC_HOLIDAY_ENTRY_SEARCH_UPDATE.php

- url: /SETTINGS/DB_PUBLIC_HOLIDAY_ENTRY.do
  script: SETTINGS/DB_PUBLIC_HOLIDAY_ENTRY.php

- url: /SETTINGS/DB_PUBLIC_HOLIDAY_SEARCH_UPDATE.do
  script: SETTINGS/DB_PUBLIC_HOLIDAY_SEARCH_UPDATE.php

- url: /SETTINGS/FORM_SETTINGS_WORK_FROM_HOME_ACCESS_SEARCH_UPDATE.do
  script: SETTINGS/FORM_SETTINGS_WORK_FROM_HOME_ACCESS_SEARCH_UPDATE.php

- url: /SETTINGS/DB_EMPLOYEE_WORK_FROM_HOME_ACCESS.do
  script: SETTINGS/DB_EMPLOYEE_WORK_FROM_HOME_ACCESS.php

- url: /SETTINGS/FORM_SETTINGS_PROJECT_ENTRY_ACCESS_SEARCH_UPDATE.do
  script: SETTINGS/FORM_SETTINGS_PROJECT_ENTRY_ACCESS_SEARCH_UPDATE.php

- url: /SETTINGS/DB_PROJECT_PROJECT_ENTRY_SEARCH_UPDATE.do
  script: SETTINGS/DB_PROJECT_PROJECT_ENTRY_SEARCH_UPDATE.php

- url: /SETTINGS/DB_EMPLOYEE_PROJECT_ACCESS.do
  script: SETTINGS/DB_EMPLOYEE_PROJECT_ACCESS.php

- url: /SETTINGS/DB_EMPLOYEE_PROJECT_SEARCH_UPDATE.do
  script: SETTINGS/DB_EMPLOYEE_PROJECT_SEARCH_UPDATE.php

- url: /ADMIN/EMPLOYEE/DB_PETTY_CASH.do
  script: ADMIN/EMPLOYEE/DB_PETTY_CASH.php

- url: /ADMIN/EMPLOYEE/FORM_PETTY_CASH.do
  script: ADMIN/EMPLOYEE/FORM_PETTY_CASH.php

- url: /ADMIN/EMPLOYEE/DB_PAYROLL.do
  script: ADMIN/EMPLOYEE/DB_PAYROLL.php

- url: /ADMIN/EMPLOYEE/FORM_PAYROLL.do
  script: ADMIN/EMPLOYEE/FORM_PAYROLL.php

- url: /ADMIN/EMPLOYEE/DB_PAYROLL_PDF.do
  script: ADMIN/EMPLOYEE/DB_PAYROLL_PDF.php

- url: /ADMIN/EMPLOYEE/DB_PAYROLL_PDF.do
  script: ADMIN/EMPLOYEE/DB_PAYROLL_PDF.php

- url: /_ah/login_required
  script: do_openid_login.py

- url: /REMAINDER_MAIL
  script: REMAINDER_MAIL.php

- url: /ABSENT_MAIL
  script: ABSENT_MAIL.php

- url: /REPORT_MAIL_USER
  script: REPORT_MAIL_USER.php

- url: /REPORT_MAIL
  script: REPORT_MAIL.php

- url: /YESTERDAY_REPORT_MAIL
  script: YESTERDAY_REPORT_MAIL.php

- url: /DROP_TEMP_TABLE
  script: DROP_TEMP_TABLE.php

- url: /ATTENDANCE_REPORT_MAIL
  script: ATTENDANCE_REPORT_MAIL.php

- url: /REPORT_MAIL_ADMIN
  script: REPORT_MAIL_ADMIN.php

- url: /TSLIB/TSLIB_COMMON_PDF.do
  script: TSLIB/TSLIB_COMMON_PDF.php

- url: .*
  script: FORM_MENU.php
  login: required