application: test-time-sheet
version: 11
runtime: php55
api_version: 1
threadsafe: true

handlers:


- url: /CSS
  static_dir: CSS

- url: /jquery
  static_dir: jquery

- url: /image
  static_dir: image

- url: /bootstrap
  static_dir: bootstrap

- url: /msgbox
  static_dir: msgbox

- url: /menu
  static_dir: menu

- url: /DATA TABLE 10.5
  static_dir: DATA TABLE 10.5

- url: /DB_MENU.do
  script: DB_MENU.php

- url: /COMMON.do
  script: COMMON.php

- url: /ERROR_PAGE.do
  script: ERROR_PAGE.php

- url: /ACCESS RIGHTS/FORM_ACCESS_RIGHTS_SEARCH_UPDATE.do
  script: ACCESS RIGHTS/FORM_ACCESS_RIGHTS_SEARCH_UPDATE.php

- url: /ACCESS RIGHTS/DB_ACCESS_RIGHTS_ACCESS_RIGHTS-SEARCH_UPDATE.do
  script: ACCESS RIGHTS/DB_ACCESS_RIGHTS_ACCESS_RIGHTS-SEARCH_UPDATE.php

- url: /FORM_ACCESS_RIGHTS_TERMINATE_SEARCH_UPDATE.do
  script: FORM_ACCESS_RIGHTS_TERMINATE_SEARCH_UPDATE.php

- url: /DB_ACCESS_RIGHTS_TERMINATE-SEARCH_UPDATE.do
  script: DB_ACCESS_RIGHTS_TERMINATE-SEARCH_UPDATE.php

- url: /FORM_ACCESS_RIGHTS_USER_SEARCH_DETAILS.do
  script: FORM_ACCESS_RIGHTS_USER_SEARCH_DETAILS.php

- url: /DB_ACCESS_RIGHTS_USER_SEARCH_DETAIL.do
  script: DB_ACCESS_RIGHTS_USER_SEARCH_DETAIL.php

- url: /FORM_ACCESS_RIGHTS_SITE_MAINTENANCE.do
  script: FORM_ACCESS_RIGHTS_SITE_MAINTENANCE.php

- url: /DB_ACCESS_RIGHTS_SITE_MAINTENANCE.do
  script: DB_ACCESS_RIGHTS_SITE_MAINTENANCE.php

- url: /ADMIN/FORM_ADMIN_REPORT_ENTRY_SEARCH_UPDATE_DELETE.do
  script: ADMIN/FORM_ADMIN_REPORT_ENTRY_SEARCH_UPDATE_DELETE.php

- url: /ADMIN/DB_DAILY_REPORTS_ADMIN_REPORT_ENTRY.do
  script: ADMIN/DB_DAILY_REPORTS_ADMIN_REPORT_ENTRY.php

- url: /ADMIN/DB_DAILY_REPORTS_ADMIN_SEARCH_UPDATE_DELETE.do
  script: ADMIN/DB_DAILY_REPORTS_ADMIN_SEARCH_UPDATE_DELETE.php

- url: /FORM_WEEKLY_REPORT_ENTRY_SEARCH_UPDATE.do
  script: FORM_WEEKLY_REPORT_ENTRY_SEARCH_UPDATE.php

- url: /DB_WEEKLY_REPORT_ADMIN_WEEKLY_REPORT_ENTRY.do
  script: DB_WEEKLY_REPORT_ADMIN_WEEKLY_REPORT_ENTRY.php

- url: /DB_WEEKLY_REPORT_ADMIN_WEEKLY_SEARCH_UPDATE.do
  script: DB_WEEKLY_REPORT_ADMIN_WEEKLY_SEARCH_UPDATE.php

- url: /FORM_ADMIN_EMPLOYEE_ATTENDANCE.do
  script: FORM_ADMIN_EMPLOYEE_ATTENDANCE.php

- url: /DB_REPORT_ATTENDANCE.do
  script: DB_REPORT_ATTENDANCE.php

- url: /FORM_ADMIN_EMPLOYEE_REVENUE.do
  script: FORM_ADMIN_EMPLOYEE_REVENUE.php

- url: /DB_REPORT_ATTENDANCE.do
  script: DB_REPORT_ATTENDANCE.php

- url: /FORM_ADMIN_EMPLOYEE_TICKLER_HISTORY.do
  script: FORM_ADMIN_EMPLOYEE_TICKLER_HISTORY.php

- url: /DB_REPORT_TICKLER_HISTORY.do
  script: DB_REPORT_TICKLER_HISTORY.php

- url: /FORM_ADMIN_EMPLOYEE_BANDWIDTH.do
  script: FORM_ADMIN_EMPLOYEE_BANDWIDTH.php

- url: /DB_REPORT_BANDWIDTH.do
  script: DB_REPORT_BANDWIDTH.php

- url: /FORM_ADMIN_EMPLOYEE_DOOR_ACCESS.do
  script: FORM_ADMIN_EMPLOYEE_DOOR_ACCESS.php

- url: /DB_REPORT_DOOR_ACCESS.do
  script: DB_REPORT_DOOR_ACCESS.php

- url: /FORM_ADMIN_EMPLOYEE_COMPANY_PROPERTY_VERIFICATION.do
  script: FORM_ADMIN_EMPLOYEE_COMPANY_PROPERTY_VERIFICATION.php

- url: /DB_EMPLOYEE_COMPANY_PROPERTY_VERIFICATION.do
  script: DB_EMPLOYEE_COMPANY_PROPERTY_VERIFICATION.php

- url: /FORM_ADMIN_EMPLOYEE_CLOCK_IN_OUT_DETAILS.do
  script: FORM_ADMIN_EMPLOYEE_CLOCK_IN_OUT_DETAILS.php

- url: /DB_REPORT_CLOCK_OUT_MISSED_DETAILS.do
  script: DB_REPORT_CLOCK_OUT_MISSED_DETAILS.php

- url: /DB_REPORT_CLOCK_IN_OUT_DETAILS.do
  script: DB_REPORT_CLOCK_IN_OUT_DETAILS.php

- url: /FORM_ADMIN_EMPLOYEE_DETAILS.do
  script: FORM_ADMIN_EMPLOYEE_DETAILS.php

- url: /DB_EMPLOYEE_DETAILS.do
  script: DB_EMPLOYEE_DETAILS.php

- url: /FORM_USER_REPORT_ENTRY_SEARCH_UPDATE.do
  script: FORM_USER_REPORT_ENTRY_SEARCH_UPDATE.php

- url: /DB_DAILY_REPORTS_USER_REPORT_ENTRY.do
  script: DB_DAILY_REPORTS_USER_REPORT_ENTRY.php

- url: /DB_DAILY_REPORTS_USER_SEARCH_UPDATE.do
  script: DB_DAILY_REPORTS_USER_SEARCH_UPDATE.php

- url: /FORM_USER_REVENUE.do
  script: FORM_USER_REVENUE.php

- url: /DB_DAILY_REPORT_USER_PROJECT_REVENUE.do
  script: DB_DAILY_REPORT_USER_PROJECT_REVENUE.php

- url: /FORM_USER_CLOCK_IN_OUT_DETAILS.do
  script: FORM_USER_CLOCK_IN_OUT_DETAILS.php

- url: /DB_DAILY_REPORTS_USER_CLOCK_IN_OUT_DETAILS.do
  script: DB_DAILY_REPORTS_USER_CLOCK_IN_OUT_DETAILS.php

- url: /DB_DAILY_REPORTS_USER_CLOCK_OUT_MISSED_DETAILS.do
  script: DB_DAILY_REPORTS_USER_CLOCK_OUT_MISSED_DETAILS.php

- url: /FORM_SETTINGS_CONFIGURATION_ENTRY_SEARCH_UPDATE_DELETE.do
  script: FORM_SETTINGS_CONFIGURATION_ENTRY_SEARCH_UPDATE_DELETE.php

- url: /DB_CONFIGURATION_ENTRY.do
  script: DB_CONFIGURATION_ENTRY.php

- url: /DB_CONFIGURATION_SEARCH_UPDATE_DELETE.do
  script: DB_CONFIGURATION_SEARCH_UPDATE_DELETE.php

- url: /FORM_SETTINGS_EMAIL_TEMPLATE_ENTRY_SEARCH_UPDATE.do
  script: FORM_SETTINGS_EMAIL_TEMPLATE_ENTRY_SEARCH_UPDATE.php

- url: /DB_EMAIL_EMAIL_TEMPLATE_ENTRY.do
  script: DB_EMAIL_EMAIL_TEMPLATE_ENTRY.php

- url: /DB_EMAIL_EMAIL_TEMPLATE_SEARCH_UPDATE.do
  script: DB_EMAIL_EMAIL_TEMPLATE_SEARCH_UPDATE.php

- url: /FORM_SETTINGS_PUBLIC_HOLIDAY_ENTRY_SEARCH_UPDATE.do
  script: FORM_SETTINGS_PUBLIC_HOLIDAY_ENTRY_SEARCH_UPDATE.php

- url: /DB_PUBLIC_HOLIDAY_ENTRY.do
  script: DB_PUBLIC_HOLIDAY_ENTRY.php

- url: /DB_PUBLIC_HOLIDAY_SEARCH_UPDATE.do
  script: DB_PUBLIC_HOLIDAY_SEARCH_UPDATE.php

- url: /FORM_SETTINGS_WORK_FROM_HOME_ACCESS_SEARCH_UPDATE.do
  script: FORM_SETTINGS_WORK_FROM_HOME_ACCESS_SEARCH_UPDATE.php

- url: /DB_EMPLOYEE_WORK_FROM_HOME_ACCESS.do
  script: DB_EMPLOYEE_WORK_FROM_HOME_ACCESS.php

- url: /FORM_SETTINGS_PROJECT_ENTRY_ACCESS_SEARCH_UPDATE.do
  script: FORM_SETTINGS_PROJECT_ENTRY_ACCESS_SEARCH_UPDATE.php

- url: /DB_PROJECT_PROJECT_ENTRY_SEARCH_UPDATE.do
  script: DB_PROJECT_PROJECT_ENTRY_SEARCH_UPDATE.php

- url: /DB_EMPLOYEE_PROJECT_ACCESS.do
  script: DB_EMPLOYEE_PROJECT_ACCESS.php

- url: /DB_EMPLOYEE_PROJECT_SEARCH_UPDATE.do
  script: DB_EMPLOYEE_PROJECT_SEARCH_UPDATE.php

- url: /_ah/login_required
  script: do_openid_login.py

- url: /REMAINDER_MAIL
  script: REMAINDER_MAIL.php

- url: /ABSENT_MAIL
  script: ABSENT_MAIL.php

- url: /REPORT_MAIL_USER
  script: REPORT_MAIL_USER.php

- url: /REPORT_MAIL
  script: REPORT_MAIL.php

- url: /YESTERDAY_REPORT_MAIL
  script: YESTERDAY_REPORT_MAIL.php

- url: /DROP_TEMP_TABLE
  script: DROP_TEMP_TABLE.php

- url: /ATTENDANCE_REPORT_MAIL
  script: ATTENDANCE_REPORT_MAIL.php

- url: /REPORT_MAIL_ADMIN
  script: REPORT_MAIL_ADMIN.php

- url: /date.do
  script: date.php

- url: /COMMON_PDF.do
  script: COMMON_PDF.php

- url: .*
  script: MENU.php
  login: required